trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: self
    - repository: AzureTemplates # ID used to reference pipeline templates below
      type: git
      name: azure-templates

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Variables
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[eq(variables['Build.Reason'], 'PullRequest')]
  workingDirectory: $(System.DefaultWorkingDirectory)

stages:
  - stage: Test
    displayName: Run tests
    jobs:
      - template: pipelines/js-test.yaml@AzureTemplates
        parameters:
          vmImageName: $(vmImageName)
          workingDirectory: $(workingDirectory)
          runE2E: true

  - stage: Publish
    displayName: Publish Bundle
    condition: and(succeeded(), and(eq(variables.isMain, 'true'), eq(variables.isPR, 'false')))
    dependsOn: Test
    variables:
      - group: azureVariables
    jobs:
      - template: pipelines/publish-bundle.yaml@AzureTemplates
        parameters:
          vmImageName: $(vmImageName)
          sourceDirectory: $(workingDirectory)
          storageAccount: $(storage-account)
